// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const isSupabaseAvailable = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export let supabaseInitError: string | null = null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createMissingSupabaseClient(message: string) {
  return new Proxy(
    {},
    {
      get() {
        throw new Error(message);
      },
    },
  ) as SupabaseClient<Database>;
}

function buildSupabaseClient() {
  if (!isSupabaseAvailable) {
    return createMissingSupabaseClient(
      "Supabase non configurato. Imposta VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY oppure usa la modalita' locale.",
    );
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== "undefined" ? window.localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (error) {
    supabaseInitError = error instanceof Error ? error.message : "Errore inizializzazione Supabase.";
    console.error("Supabase init error:", error);
    return createMissingSupabaseClient(
      `Configurazione Supabase non valida: ${supabaseInitError}`,
    );
  }
}

export const supabase = buildSupabaseClient();
export const isSupabaseReady = isSupabaseAvailable && !supabaseInitError;
